// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module newsob_Filter2D (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        p_src_rows_V_read,
        p_src_cols_V_read,
        p_src_data_stream_V_dout,
        p_src_data_stream_V_empty_n,
        p_src_data_stream_V_read,
        p_dst_data_stream_V_din,
        p_dst_data_stream_V_full_n,
        p_dst_data_stream_V_write
);

parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_ST_st1_fsm_0 = 7'b1;
parameter    ap_ST_st2_fsm_1 = 7'b10;
parameter    ap_ST_st3_fsm_2 = 7'b100;
parameter    ap_ST_st4_fsm_3 = 7'b1000;
parameter    ap_ST_st5_fsm_4 = 7'b10000;
parameter    ap_ST_pp0_stg0_fsm_5 = 7'b100000;
parameter    ap_ST_st16_fsm_6 = 7'b1000000;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv1_1 = 1'b1;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_lv32_2 = 32'b10;
parameter    ap_const_lv32_3 = 32'b11;
parameter    ap_const_lv32_4 = 32'b100;
parameter    ap_const_lv32_5 = 32'b101;
parameter    ap_const_lv12_0 = 12'b000000000000;
parameter    ap_const_lv32_6 = 32'b110;
parameter    ap_const_lv13_2 = 13'b10;
parameter    ap_const_lv2_3 = 2'b11;
parameter    ap_const_lv12_1 = 12'b1;
parameter    ap_const_lv14_2 = 14'b10;
parameter    ap_const_lv14_3FFE = 14'b11111111111110;
parameter    ap_const_lv32_B = 32'b1011;
parameter    ap_const_lv11_0 = 11'b00000000000;
parameter    ap_const_lv13_1FFF = 13'b1111111111111;
parameter    ap_const_lv32_C = 32'b1100;
parameter    ap_const_lv13_1 = 13'b1;
parameter    ap_const_lv13_1FFE = 13'b1111111111110;
parameter    ap_const_lv13_1FFD = 13'b1111111111101;
parameter    ap_const_lv13_3 = 13'b11;
parameter    ap_const_lv2_0 = 2'b00;
parameter    ap_const_lv13_0 = 13'b0000000000000;
parameter    ap_const_lv8_0 = 8'b00000000;
parameter    ap_const_lv10_0 = 10'b0000000000;
parameter    ap_const_lv9_0 = 9'b000000000;
parameter    ap_const_lv32_A = 32'b1010;
parameter    ap_const_lv32_8 = 32'b1000;
parameter    ap_const_lv3_0 = 3'b000;
parameter    ap_const_lv8_FF = 8'b11111111;
parameter    ap_true = 1'b1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [11:0] p_src_rows_V_read;
input  [11:0] p_src_cols_V_read;
input  [7:0] p_src_data_stream_V_dout;
input   p_src_data_stream_V_empty_n;
output   p_src_data_stream_V_read;
output  [7:0] p_dst_data_stream_V_din;
input   p_dst_data_stream_V_full_n;
output   p_dst_data_stream_V_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg p_src_data_stream_V_read;
reg p_dst_data_stream_V_write;
(* fsm_encoding = "none" *) reg   [6:0] ap_CS_fsm = 7'b1;
reg    ap_sig_cseq_ST_st1_fsm_0;
reg    ap_sig_bdd_25;
reg   [11:0] p_027_0_i_reg_272;
wire   [12:0] rows_cast_fu_283_p1;
reg   [12:0] rows_cast_reg_1283;
wire   [12:0] cols_cast_fu_287_p1;
reg   [12:0] cols_cast_reg_1294;
wire   [0:0] tmp_7_fu_291_p2;
reg    ap_sig_cseq_ST_st2_fsm_1;
reg    ap_sig_bdd_60;
wire   [12:0] heightloop_fu_297_p2;
reg   [12:0] heightloop_reg_1380;
wire   [0:0] tmp_6_phi_fu_254_p4;
wire   [12:0] widthloop_fu_302_p2;
reg   [12:0] widthloop_reg_1385;
wire   [1:0] p_neg391_i_cast_fu_310_p2;
reg   [1:0] p_neg391_i_cast_reg_1390;
wire   [12:0] p_anchor_2_1_cast_fu_324_p1;
reg   [12:0] p_anchor_2_1_cast_reg_1397;
wire   [0:0] tmp_1_fu_328_p2;
reg   [0:0] tmp_1_reg_1402;
wire   [13:0] tmp_8_fu_344_p2;
reg   [13:0] tmp_8_reg_1409;
wire   [0:0] tmp_9_fu_350_p2;
reg   [0:0] tmp_9_reg_1416;
wire   [13:0] tmp_2_fu_366_p2;
reg   [13:0] tmp_2_reg_1421;
wire   [1:0] tmp_3_fu_372_p2;
reg   [1:0] tmp_3_reg_1426;
wire   [11:0] i_V_fu_387_p2;
reg   [11:0] i_V_reg_1434;
reg    ap_sig_cseq_ST_st3_fsm_2;
reg    ap_sig_bdd_91;
wire   [0:0] tmp_11_fu_393_p2;
reg   [0:0] tmp_11_reg_1439;
wire   [0:0] tmp_4_fu_382_p2;
wire   [0:0] ult_fu_398_p2;
reg   [0:0] ult_reg_1443;
wire   [0:0] icmp_fu_413_p2;
reg   [0:0] icmp_reg_1448;
wire   [0:0] tmp_12_fu_419_p2;
reg   [0:0] tmp_12_reg_1453;
wire   [0:0] tmp_111_1_fu_424_p2;
reg   [0:0] tmp_111_1_reg_1457;
wire   [0:0] tmp_111_2_fu_430_p2;
reg   [0:0] tmp_111_2_reg_1461;
wire   [0:0] tmp_13_fu_436_p2;
reg   [0:0] tmp_13_reg_1465;
reg   [0:0] tmp_22_reg_1472;
wire   [0:0] tmp_16_fu_455_p2;
reg   [0:0] tmp_16_reg_1477;
wire   [12:0] p_p2_i423_i_fu_474_p3;
reg   [12:0] p_p2_i423_i_reg_1482;
reg   [0:0] tmp_27_reg_1487;
wire   [0:0] tmp_137_1_fu_503_p2;
reg   [0:0] tmp_137_1_reg_1492;
wire   [12:0] p_p2_i423_i_1_fu_522_p3;
reg   [12:0] p_p2_i423_i_1_reg_1497;
reg   [0:0] tmp_33_reg_1502;
wire   [0:0] tmp_137_2_fu_551_p2;
reg   [0:0] tmp_137_2_reg_1507;
wire   [12:0] p_p2_i423_i_2_fu_570_p3;
reg   [12:0] p_p2_i423_i_2_reg_1512;
wire   [1:0] tmp_47_fu_585_p1;
reg   [1:0] tmp_47_reg_1517;
wire   [1:0] tmp_49_fu_589_p1;
reg   [1:0] tmp_49_reg_1522;
wire   [1:0] tmp_53_fu_593_p2;
reg   [1:0] tmp_53_reg_1527;
wire   [1:0] tmp_55_fu_599_p1;
reg   [1:0] tmp_55_reg_1532;
wire   [1:0] tmp_56_fu_603_p1;
reg   [1:0] tmp_56_reg_1537;
wire   [1:0] tmp_58_fu_607_p2;
reg   [1:0] tmp_58_reg_1542;
wire   [1:0] tmp_59_fu_613_p1;
reg   [1:0] tmp_59_reg_1547;
wire   [1:0] tmp_60_fu_617_p1;
reg   [1:0] tmp_60_reg_1552;
wire   [1:0] tmp_61_fu_621_p2;
reg   [1:0] tmp_61_reg_1557;
wire   [0:0] brmerge1_fu_669_p2;
reg   [0:0] brmerge1_reg_1562;
reg    ap_sig_cseq_ST_st4_fsm_3;
reg    ap_sig_bdd_154;
wire   [1:0] tmp_19_fu_674_p3;
reg   [1:0] tmp_19_reg_1567;
wire   [1:0] tmp_37_fu_681_p3;
reg   [1:0] tmp_37_reg_1572;
wire   [0:0] brmerge2_fu_687_p2;
reg   [0:0] brmerge2_reg_1577;
wire   [1:0] tmp_43_fu_692_p3;
reg   [1:0] tmp_43_reg_1582;
wire   [1:0] tmp_44_fu_699_p3;
reg   [1:0] tmp_44_reg_1587;
wire   [0:0] brmerge3_fu_705_p2;
reg   [0:0] brmerge3_reg_1592;
wire   [1:0] tmp_48_fu_710_p3;
reg   [1:0] tmp_48_reg_1597;
wire   [1:0] tmp_54_fu_717_p3;
reg   [1:0] tmp_54_reg_1602;
wire   [0:0] rev_fu_723_p2;
reg   [0:0] rev_reg_1607;
reg    ap_sig_cseq_ST_st5_fsm_4;
reg    ap_sig_bdd_182;
wire   [1:0] row_assign_9_fu_733_p2;
reg   [1:0] row_assign_9_reg_1612;
wire   [1:0] row_assign_9_1_t_fu_743_p2;
reg   [1:0] row_assign_9_1_t_reg_1617;
wire   [1:0] row_assign_9_2_t_fu_753_p2;
reg   [1:0] row_assign_9_2_t_reg_1622;
wire   [0:0] tmp_20_fu_762_p2;
reg   [0:0] tmp_20_reg_1627;
reg    ap_sig_cseq_ST_pp0_stg0_fsm_5;
reg    ap_sig_bdd_198;
reg    ap_reg_ppiten_pp0_it0 = 1'b0;
reg    ap_reg_ppiten_pp0_it1 = 1'b0;
reg    ap_reg_ppiten_pp0_it2 = 1'b0;
reg    ap_reg_ppiten_pp0_it3 = 1'b0;
reg   [0:0] ap_reg_ppstg_tmp_20_reg_1627_pp0_it3;
reg   [0:0] or_cond_i_i_reg_1662;
reg   [0:0] ap_reg_ppstg_or_cond_i_i_reg_1662_pp0_it3;
reg    ap_sig_bdd_227;
reg    ap_reg_ppiten_pp0_it4 = 1'b0;
reg    ap_reg_ppiten_pp0_it5 = 1'b0;
reg    ap_reg_ppiten_pp0_it6 = 1'b0;
reg    ap_reg_ppiten_pp0_it7 = 1'b0;
reg    ap_reg_ppiten_pp0_it8 = 1'b0;
reg   [0:0] or_cond_i_reg_1658;
reg   [0:0] ap_reg_ppstg_or_cond_i_reg_1658_pp0_it8;
reg    ap_sig_bdd_245;
reg    ap_reg_ppiten_pp0_it9 = 1'b0;
reg   [0:0] ap_reg_ppstg_tmp_20_reg_1627_pp0_it1;
reg   [0:0] ap_reg_ppstg_tmp_20_reg_1627_pp0_it2;
reg   [0:0] ap_reg_ppstg_tmp_20_reg_1627_pp0_it4;
reg   [0:0] ap_reg_ppstg_tmp_20_reg_1627_pp0_it5;
wire   [11:0] j_V_fu_767_p2;
wire   [12:0] ImagLoc_x_fu_789_p2;
reg   [12:0] ImagLoc_x_reg_1636;
wire   [0:0] rev4_fu_803_p2;
reg   [0:0] rev4_reg_1641;
wire   [0:0] tmp_25_fu_809_p2;
reg   [0:0] tmp_25_reg_1646;
wire   [12:0] p_p2_i_i_fu_828_p3;
reg   [12:0] p_p2_i_i_reg_1652;
wire   [0:0] or_cond_i_fu_836_p2;
reg   [0:0] ap_reg_ppstg_or_cond_i_reg_1658_pp0_it1;
reg   [0:0] ap_reg_ppstg_or_cond_i_reg_1658_pp0_it2;
reg   [0:0] ap_reg_ppstg_or_cond_i_reg_1658_pp0_it3;
reg   [0:0] ap_reg_ppstg_or_cond_i_reg_1658_pp0_it4;
reg   [0:0] ap_reg_ppstg_or_cond_i_reg_1658_pp0_it5;
reg   [0:0] ap_reg_ppstg_or_cond_i_reg_1658_pp0_it6;
reg   [0:0] ap_reg_ppstg_or_cond_i_reg_1658_pp0_it7;
wire   [0:0] or_cond_i_i_fu_841_p2;
reg   [0:0] ap_reg_ppstg_or_cond_i_i_reg_1662_pp0_it2;
reg   [0:0] ap_reg_ppstg_or_cond_i_i_reg_1662_pp0_it4;
wire  signed [13:0] p_p2_i_i_cast_fu_861_p1;
reg  signed [13:0] p_p2_i_i_cast_reg_1666;
wire   [0:0] tmp_28_fu_864_p2;
reg   [0:0] tmp_28_reg_1671;
wire   [13:0] sel_tmp_fu_873_p3;
reg   [13:0] sel_tmp_reg_1676;
wire   [0:0] sel_tmp7_fu_881_p2;
reg   [0:0] sel_tmp7_reg_1681;
wire   [0:0] brmerge_fu_887_p2;
reg   [0:0] brmerge_reg_1686;
reg   [0:0] ap_reg_ppstg_brmerge_reg_1686_pp0_it2;
reg   [0:0] ap_reg_ppstg_brmerge_reg_1686_pp0_it3;
wire   [13:0] x_fu_895_p3;
reg   [13:0] x_reg_1693;
wire   [1:0] col_assign_2_t_fu_905_p2;
reg   [1:0] col_assign_2_t_reg_1698;
reg   [1:0] ap_reg_ppstg_col_assign_2_t_reg_1698_pp0_it3;
reg   [9:0] k_buf_0_val_3_addr_reg_1705;
reg   [9:0] k_buf_0_val_4_addr_reg_1711;
reg   [9:0] ap_reg_ppstg_k_buf_0_val_4_addr_reg_1711_pp0_it4;
reg   [9:0] k_buf_0_val_5_addr_reg_1717;
reg   [9:0] ap_reg_ppstg_k_buf_0_val_5_addr_reg_1717_pp0_it4;
wire   [7:0] k_buf_0_val_3_q0;
reg   [7:0] k_buf_0_val_3_load_reg_1723;
wire   [7:0] col_buf_0_val_0_0_fu_949_p3;
reg   [7:0] col_buf_0_val_0_0_reg_1728;
wire   [7:0] k_buf_0_val_4_q0;
reg   [7:0] k_buf_0_val_4_load_reg_1736;
wire   [7:0] col_buf_0_val_1_0_fu_967_p3;
reg   [7:0] col_buf_0_val_1_0_reg_1741;
wire   [7:0] col_buf_0_val_2_0_fu_985_p3;
reg   [7:0] col_buf_0_val_2_0_reg_1749;
reg   [7:0] tmp_71_reg_1757;
wire   [7:0] src_kernel_win_0_val_0_0_fu_1036_p3;
reg   [7:0] src_kernel_win_0_val_0_0_reg_1763;
wire   [7:0] src_kernel_win_0_val_1_0_fu_1050_p3;
reg   [7:0] src_kernel_win_0_val_1_0_reg_1769;
reg   [7:0] ap_reg_ppstg_src_kernel_win_0_val_1_0_reg_1769_pp0_it6;
wire   [7:0] src_kernel_win_0_val_2_0_fu_1064_p3;
reg   [7:0] src_kernel_win_0_val_2_0_reg_1775;
wire   [10:0] tmp25_fu_1135_p2;
reg   [10:0] tmp25_reg_1781;
wire   [9:0] tmp27_fu_1141_p2;
reg   [9:0] tmp27_reg_1786;
wire   [0:0] isneg_fu_1208_p3;
reg   [0:0] isneg_reg_1791;
wire   [7:0] p_Val2_4_fu_1216_p1;
reg   [7:0] p_Val2_4_reg_1796;
wire   [0:0] tmp_2_i_i_fu_1230_p2;
reg   [0:0] tmp_2_i_i_reg_1801;
wire   [0:0] not_i_i_i_fu_1236_p2;
reg   [0:0] not_i_i_i_reg_1807;
wire   [7:0] p_Val2_s_fu_1258_p3;
reg   [7:0] p_Val2_s_reg_1812;
wire   [9:0] k_buf_0_val_3_address0;
reg    k_buf_0_val_3_ce0;
wire   [9:0] k_buf_0_val_3_address1;
reg    k_buf_0_val_3_ce1;
reg    k_buf_0_val_3_we1;
wire   [7:0] k_buf_0_val_3_d1;
wire   [9:0] k_buf_0_val_4_address0;
reg    k_buf_0_val_4_ce0;
wire   [9:0] k_buf_0_val_4_address1;
reg    k_buf_0_val_4_ce1;
reg    k_buf_0_val_4_we1;
reg   [7:0] k_buf_0_val_4_d1;
wire   [9:0] k_buf_0_val_5_address0;
reg    k_buf_0_val_5_ce0;
wire   [7:0] k_buf_0_val_5_q0;
wire   [9:0] k_buf_0_val_5_address1;
reg    k_buf_0_val_5_ce1;
reg    k_buf_0_val_5_we1;
reg   [7:0] k_buf_0_val_5_d1;
reg   [0:0] tmp_6_reg_250;
reg   [11:0] p_014_0_i_reg_261;
reg    ap_sig_cseq_ST_st16_fsm_6;
reg    ap_sig_bdd_420;
wire   [63:0] tmp_29_fu_913_p1;
reg   [7:0] src_kernel_win_0_val_0_1_fu_134;
reg   [7:0] src_kernel_win_0_val_0_1_1_fu_138;
reg   [7:0] src_kernel_win_0_val_1_1_fu_142;
reg   [7:0] src_kernel_win_0_val_1_1_1_fu_146;
reg   [7:0] src_kernel_win_0_val_2_1_fu_150;
reg   [7:0] src_kernel_win_0_val_2_1_1_fu_154;
reg   [7:0] right_border_buf_0_val_0_1_fu_158;
reg   [7:0] right_border_buf_0_val_0_1_1_fu_162;
reg   [7:0] right_border_buf_0_val_2_1_fu_166;
reg   [7:0] right_border_buf_0_val_1_1_fu_170;
reg   [7:0] right_border_buf_0_val_1_1_1_fu_174;
reg   [7:0] right_border_buf_0_val_2_1_1_fu_178;
wire   [1:0] tmp_fu_307_p1;
wire   [0:0] not_tmp_s_fu_319_p2;
wire   [12:0] tmp_5_fu_333_p3;
wire   [13:0] tmp_149_cast_fu_340_p1;
wire   [12:0] tmp_s_fu_355_p3;
wire   [13:0] tmp_29_cast_fu_362_p1;
wire   [1:0] tmp_14_fu_316_p1;
wire   [12:0] tmp_15_cast_fu_378_p1;
wire   [10:0] tmp_18_fu_403_p4;
wire   [12:0] tmp_15_fu_441_p2;
wire   [0:0] tmp_23_fu_460_p3;
wire   [12:0] p_assign_7_fu_468_p2;
wire   [12:0] p_assign_6_1_fu_489_p2;
wire   [0:0] tmp_30_fu_508_p3;
wire   [12:0] p_assign_7_1_fu_516_p2;
wire   [12:0] p_assign_6_2_fu_537_p2;
wire   [0:0] tmp_38_fu_556_p3;
wire   [12:0] p_assign_7_2_fu_564_p2;
wire   [1:0] tmp_24_fu_482_p1;
wire   [1:0] tmp_26_fu_485_p1;
wire   [1:0] tmp_31_fu_530_p1;
wire   [1:0] tmp_32_fu_533_p1;
wire   [1:0] tmp_39_fu_578_p1;
wire   [1:0] tmp_42_fu_581_p1;
wire   [0:0] rev1_fu_627_p2;
wire   [0:0] rev2_fu_641_p2;
wire   [0:0] rev3_fu_655_p2;
wire   [0:0] or_cond_i422_i_fu_632_p2;
wire   [0:0] tmp_17_fu_637_p2;
wire   [0:0] or_cond_i422_i_1_fu_646_p2;
wire   [0:0] tmp_147_1_fu_651_p2;
wire   [0:0] or_cond_i422_i_2_fu_660_p2;
wire   [0:0] tmp_147_2_fu_665_p2;
wire   [1:0] tmp_40_fu_728_p3;
wire   [1:0] tmp_45_fu_738_p3;
wire   [1:0] tmp_50_fu_748_p3;
wire   [12:0] tmp_19_cast_fu_758_p1;
wire   [10:0] tmp_62_fu_773_p4;
wire   [0:0] tmp_63_fu_795_p3;
wire   [0:0] tmp_64_fu_814_p3;
wire   [12:0] p_assign_1_fu_822_p2;
wire   [0:0] icmp1_fu_783_p2;
wire   [12:0] ImagLoc_x_cast_mux_fu_850_p3;
wire   [0:0] brmerge9_fu_845_p2;
wire   [13:0] ImagLoc_x_cast_mux_cast_fu_857_p1;
wire   [13:0] p_assign_2_fu_868_p2;
wire   [0:0] sel_tmp8_fu_891_p2;
wire   [1:0] tmp_65_fu_901_p1;
wire  signed [31:0] col_assign_cast_fu_910_p1;
wire   [7:0] tmp_34_fu_938_p5;
wire   [7:0] tmp_35_fu_956_p5;
wire   [7:0] tmp_36_fu_974_p5;
wire   [7:0] tmp_41_fu_1028_p5;
wire   [7:0] tmp_46_fu_1042_p5;
wire   [7:0] tmp_51_fu_1056_p5;
wire   [8:0] tmp_155_0_2_cast_fu_1083_p1;
wire   [8:0] OP1_V_0_cast_fu_1079_p1;
wire   [8:0] p_Val2_5_0_2_fu_1086_p2;
wire   [8:0] p_shl_fu_1096_p3;
wire   [9:0] p_shl_cast_fu_1104_p1;
wire   [9:0] p_Val2_1_fu_1108_p2;
wire   [8:0] OP1_V_2_cast_fu_1118_p1;
wire   [8:0] p_Val2_2_fu_1122_p2;
wire  signed [10:0] tmp_155_2_cast_fu_1128_p1;
wire  signed [10:0] tmp_155_1_cast_fu_1114_p1;
wire   [9:0] tmp_155_2_2_cast_cast_fu_1132_p1;
wire  signed [9:0] p_Val2_5_0_2_cast_cast_fu_1092_p1;
wire   [8:0] p_Val2_1_2_fu_1183_p3;
wire   [10:0] tmp_155_1_cast_38_fu_1190_p1;
wire  signed [10:0] tmp27_cast_fu_1194_p1;
wire   [10:0] tmp26_fu_1197_p2;
wire   [10:0] p_Val2_3_fu_1203_p2;
wire   [2:0] tmp_52_fu_1220_p4;
wire   [0:0] overflow_fu_1242_p2;
wire   [0:0] tmp_i_i_fu_1253_p2;
wire   [7:0] p_mux_i_i_cast_fu_1246_p3;
reg   [6:0] ap_NS_fsm;
reg    ap_sig_bdd_1131;
reg    ap_sig_bdd_1133;
reg    ap_sig_bdd_1130;
reg    ap_sig_bdd_1136;


newsob_Filter2D_k_buf_0_val_3 #(
    .DataWidth( 8 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
k_buf_0_val_3_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( k_buf_0_val_3_address0 ),
    .ce0( k_buf_0_val_3_ce0 ),
    .q0( k_buf_0_val_3_q0 ),
    .address1( k_buf_0_val_3_address1 ),
    .ce1( k_buf_0_val_3_ce1 ),
    .we1( k_buf_0_val_3_we1 ),
    .d1( k_buf_0_val_3_d1 )
);

newsob_Filter2D_k_buf_0_val_3 #(
    .DataWidth( 8 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
k_buf_0_val_4_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( k_buf_0_val_4_address0 ),
    .ce0( k_buf_0_val_4_ce0 ),
    .q0( k_buf_0_val_4_q0 ),
    .address1( k_buf_0_val_4_address1 ),
    .ce1( k_buf_0_val_4_ce1 ),
    .we1( k_buf_0_val_4_we1 ),
    .d1( k_buf_0_val_4_d1 )
);

newsob_Filter2D_k_buf_0_val_3 #(
    .DataWidth( 8 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
k_buf_0_val_5_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( k_buf_0_val_5_address0 ),
    .ce0( k_buf_0_val_5_ce0 ),
    .q0( k_buf_0_val_5_q0 ),
    .address1( k_buf_0_val_5_address1 ),
    .ce1( k_buf_0_val_5_ce1 ),
    .we1( k_buf_0_val_5_we1 ),
    .d1( k_buf_0_val_5_d1 )
);

newsob_mux_3to1_sel2_8_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
newsob_mux_3to1_sel2_8_1_U14(
    .din1( right_border_buf_0_val_0_1_fu_158 ),
    .din2( right_border_buf_0_val_0_1_1_fu_162 ),
    .din3( ap_const_lv8_0 ),
    .din4( ap_reg_ppstg_col_assign_2_t_reg_1698_pp0_it3 ),
    .dout( tmp_34_fu_938_p5 )
);

newsob_mux_3to1_sel2_8_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
newsob_mux_3to1_sel2_8_1_U15(
    .din1( right_border_buf_0_val_1_1_fu_170 ),
    .din2( right_border_buf_0_val_1_1_1_fu_174 ),
    .din3( ap_const_lv8_0 ),
    .din4( ap_reg_ppstg_col_assign_2_t_reg_1698_pp0_it3 ),
    .dout( tmp_35_fu_956_p5 )
);

newsob_mux_3to1_sel2_8_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
newsob_mux_3to1_sel2_8_1_U16(
    .din1( right_border_buf_0_val_2_1_1_fu_178 ),
    .din2( right_border_buf_0_val_2_1_fu_166 ),
    .din3( ap_const_lv8_0 ),
    .din4( ap_reg_ppstg_col_assign_2_t_reg_1698_pp0_it3 ),
    .dout( tmp_36_fu_974_p5 )
);

newsob_mux_3to1_sel2_8_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
newsob_mux_3to1_sel2_8_1_U17(
    .din1( col_buf_0_val_0_0_reg_1728 ),
    .din2( col_buf_0_val_1_0_reg_1741 ),
    .din3( col_buf_0_val_2_0_reg_1749 ),
    .din4( row_assign_9_reg_1612 ),
    .dout( tmp_41_fu_1028_p5 )
);

newsob_mux_3to1_sel2_8_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
newsob_mux_3to1_sel2_8_1_U18(
    .din1( col_buf_0_val_0_0_reg_1728 ),
    .din2( col_buf_0_val_1_0_reg_1741 ),
    .din3( col_buf_0_val_2_0_reg_1749 ),
    .din4( row_assign_9_1_t_reg_1617 ),
    .dout( tmp_46_fu_1042_p5 )
);

newsob_mux_3to1_sel2_8_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
newsob_mux_3to1_sel2_8_1_U19(
    .din1( col_buf_0_val_0_0_reg_1728 ),
    .din2( col_buf_0_val_1_0_reg_1741 ),
    .din3( col_buf_0_val_2_0_reg_1749 ),
    .din4( row_assign_9_2_t_reg_1622 ),
    .dout( tmp_51_fu_1056_p5 )
);



always @ (posedge ap_clk) begin : ap_ret_ap_CS_fsm
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it0
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_5) & ~((ap_sig_bdd_227 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_245 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it9))) & (ap_const_lv1_0 == tmp_20_fu_762_p2))) begin
            ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
        end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4)) begin
            ap_reg_ppiten_pp0_it0 <= ap_const_logic_1;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it1
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_5) & ~((ap_sig_bdd_227 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_245 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it9))))) begin
            ap_reg_ppiten_pp0_it1 <= ap_reg_ppiten_pp0_it0;
        end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4)) begin
            ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it2
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it2 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_227 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_245 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it9)))) begin
            ap_reg_ppiten_pp0_it2 <= ap_reg_ppiten_pp0_it1;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it3
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it3 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_227 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_245 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it9)))) begin
            ap_reg_ppiten_pp0_it3 <= ap_reg_ppiten_pp0_it2;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it4
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it4 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_227 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_245 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it9)))) begin
            ap_reg_ppiten_pp0_it4 <= ap_reg_ppiten_pp0_it3;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it5
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it5 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_227 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_245 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it9)))) begin
            if (~(ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) begin
                ap_reg_ppiten_pp0_it5 <= ap_const_logic_0;
            end else if ((ap_const_logic_1 == ap_reg_ppiten_pp0_it3)) begin
                ap_reg_ppiten_pp0_it5 <= ap_reg_ppiten_pp0_it4;
            end
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it6
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it6 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_227 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_245 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it9)))) begin
            ap_reg_ppiten_pp0_it6 <= ap_reg_ppiten_pp0_it5;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it7
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it7 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_227 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_245 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it9)))) begin
            ap_reg_ppiten_pp0_it7 <= ap_reg_ppiten_pp0_it6;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it8
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it8 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_227 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_245 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it9)))) begin
            ap_reg_ppiten_pp0_it8 <= ap_reg_ppiten_pp0_it7;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it9
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it9 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_227 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_245 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it9)))) begin
            ap_reg_ppiten_pp0_it9 <= ap_reg_ppiten_pp0_it8;
        end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4)) begin
            ap_reg_ppiten_pp0_it9 <= ap_const_logic_0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st16_fsm_6)) begin
        p_014_0_i_reg_261 <= i_V_reg_1434;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (tmp_6_phi_fu_254_p4 == ap_const_lv1_0))) begin
        p_014_0_i_reg_261 <= ap_const_lv12_0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_5) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_227 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_245 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it9))) & ~(ap_const_lv1_0 == tmp_20_fu_762_p2))) begin
        p_027_0_i_reg_272 <= j_V_fu_767_p2;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4)) begin
        p_027_0_i_reg_272 <= ap_const_lv12_0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == ap_const_logic_0))) begin
        tmp_6_reg_250 <= ap_const_lv1_0;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & ~(tmp_6_phi_fu_254_p4 == ap_const_lv1_0))) begin
        tmp_6_reg_250 <= tmp_7_fu_291_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_5) & ~((ap_sig_bdd_227 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_245 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it9))) & ~(ap_const_lv1_0 == tmp_20_fu_762_p2))) begin
        ImagLoc_x_reg_1636 <= ImagLoc_x_fu_789_p2;
        or_cond_i_reg_1658 <= or_cond_i_fu_836_p2;
        p_p2_i_i_reg_1652 <= p_p2_i_i_fu_828_p3;
        rev4_reg_1641 <= rev4_fu_803_p2;
        tmp_25_reg_1646 <= tmp_25_fu_809_p2;
    end
end

always @ (posedge ap_clk) begin
    if (~((ap_sig_bdd_227 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_245 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it9)))) begin
        ap_reg_ppstg_brmerge_reg_1686_pp0_it2 <= brmerge_reg_1686;
        ap_reg_ppstg_brmerge_reg_1686_pp0_it3 <= ap_reg_ppstg_brmerge_reg_1686_pp0_it2;
        ap_reg_ppstg_col_assign_2_t_reg_1698_pp0_it3 <= col_assign_2_t_reg_1698;
        ap_reg_ppstg_k_buf_0_val_4_addr_reg_1711_pp0_it4 <= k_buf_0_val_4_addr_reg_1711;
        ap_reg_ppstg_k_buf_0_val_5_addr_reg_1717_pp0_it4 <= k_buf_0_val_5_addr_reg_1717;
        ap_reg_ppstg_or_cond_i_i_reg_1662_pp0_it2 <= or_cond_i_i_reg_1662;
        ap_reg_ppstg_or_cond_i_i_reg_1662_pp0_it3 <= ap_reg_ppstg_or_cond_i_i_reg_1662_pp0_it2;
        ap_reg_ppstg_or_cond_i_i_reg_1662_pp0_it4 <= ap_reg_ppstg_or_cond_i_i_reg_1662_pp0_it3;
        ap_reg_ppstg_or_cond_i_reg_1658_pp0_it2 <= ap_reg_ppstg_or_cond_i_reg_1658_pp0_it1;
        ap_reg_ppstg_or_cond_i_reg_1658_pp0_it3 <= ap_reg_ppstg_or_cond_i_reg_1658_pp0_it2;
        ap_reg_ppstg_or_cond_i_reg_1658_pp0_it4 <= ap_reg_ppstg_or_cond_i_reg_1658_pp0_it3;
        ap_reg_ppstg_or_cond_i_reg_1658_pp0_it5 <= ap_reg_ppstg_or_cond_i_reg_1658_pp0_it4;
        ap_reg_ppstg_or_cond_i_reg_1658_pp0_it6 <= ap_reg_ppstg_or_cond_i_reg_1658_pp0_it5;
        ap_reg_ppstg_or_cond_i_reg_1658_pp0_it7 <= ap_reg_ppstg_or_cond_i_reg_1658_pp0_it6;
        ap_reg_ppstg_or_cond_i_reg_1658_pp0_it8 <= ap_reg_ppstg_or_cond_i_reg_1658_pp0_it7;
        ap_reg_ppstg_src_kernel_win_0_val_1_0_reg_1769_pp0_it6 <= src_kernel_win_0_val_1_0_reg_1769;
        ap_reg_ppstg_tmp_20_reg_1627_pp0_it2 <= ap_reg_ppstg_tmp_20_reg_1627_pp0_it1;
        ap_reg_ppstg_tmp_20_reg_1627_pp0_it3 <= ap_reg_ppstg_tmp_20_reg_1627_pp0_it2;
        ap_reg_ppstg_tmp_20_reg_1627_pp0_it4 <= ap_reg_ppstg_tmp_20_reg_1627_pp0_it3;
        ap_reg_ppstg_tmp_20_reg_1627_pp0_it5 <= ap_reg_ppstg_tmp_20_reg_1627_pp0_it4;
        src_kernel_win_0_val_0_0_reg_1763 <= src_kernel_win_0_val_0_0_fu_1036_p3;
        src_kernel_win_0_val_1_0_reg_1769 <= src_kernel_win_0_val_1_0_fu_1050_p3;
        src_kernel_win_0_val_2_0_reg_1775 <= src_kernel_win_0_val_2_0_fu_1064_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_5) & ~((ap_sig_bdd_227 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_245 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it9))))) begin
        ap_reg_ppstg_or_cond_i_reg_1658_pp0_it1 <= or_cond_i_reg_1658;
        ap_reg_ppstg_tmp_20_reg_1627_pp0_it1 <= tmp_20_reg_1627;
        tmp_20_reg_1627 <= tmp_20_fu_762_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & ~(ap_const_lv1_0 == tmp_13_reg_1465))) begin
        brmerge1_reg_1562 <= brmerge1_fu_669_p2;
        brmerge2_reg_1577 <= brmerge2_fu_687_p2;
        brmerge3_reg_1592 <= brmerge3_fu_705_p2;
        tmp_19_reg_1567 <= tmp_19_fu_674_p3;
        tmp_37_reg_1572 <= tmp_37_fu_681_p3;
        tmp_43_reg_1582 <= tmp_43_fu_692_p3;
        tmp_44_reg_1587 <= tmp_44_fu_699_p3;
        tmp_48_reg_1597 <= tmp_48_fu_710_p3;
        tmp_54_reg_1602 <= tmp_54_fu_717_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_5) & ~((ap_sig_bdd_227 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_245 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it9))) & ~(ap_const_lv1_0 == tmp_20_reg_1627))) begin
        brmerge_reg_1686 <= brmerge_fu_887_p2;
        or_cond_i_i_reg_1662 <= or_cond_i_i_fu_841_p2;
        p_p2_i_i_cast_reg_1666 <= p_p2_i_i_cast_fu_861_p1;
        sel_tmp7_reg_1681 <= sel_tmp7_fu_881_p2;
        sel_tmp_reg_1676 <= sel_tmp_fu_873_p3;
        tmp_28_reg_1671 <= tmp_28_fu_864_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_sig_bdd_227 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_245 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it9))) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_20_reg_1627_pp0_it1))) begin
        col_assign_2_t_reg_1698 <= col_assign_2_t_fu_905_p2;
        x_reg_1693 <= x_fu_895_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((~(ap_const_lv1_0 == ap_reg_ppstg_tmp_20_reg_1627_pp0_it3) & ~((ap_sig_bdd_227 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_245 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it9))))) begin
        col_buf_0_val_0_0_reg_1728 <= col_buf_0_val_0_0_fu_949_p3;
        col_buf_0_val_1_0_reg_1741 <= col_buf_0_val_1_0_fu_967_p3;
        col_buf_0_val_2_0_reg_1749 <= col_buf_0_val_2_0_fu_985_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == ap_const_logic_0))) begin
        cols_cast_reg_1294[11 : 0] <= cols_cast_fu_287_p1[11 : 0];
        rows_cast_reg_1283[11 : 0] <= rows_cast_fu_283_p1[11 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (tmp_6_phi_fu_254_p4 == ap_const_lv1_0))) begin
        heightloop_reg_1380 <= heightloop_fu_297_p2;
        p_anchor_2_1_cast_reg_1397[0] <= p_anchor_2_1_cast_fu_324_p1[0];
        p_neg391_i_cast_reg_1390 <= p_neg391_i_cast_fu_310_p2;
        tmp_1_reg_1402 <= tmp_1_fu_328_p2;
        tmp_2_reg_1421[13 : 1] <= tmp_2_fu_366_p2[13 : 1];
        tmp_3_reg_1426 <= tmp_3_fu_372_p2;
        tmp_8_reg_1409[13 : 1] <= tmp_8_fu_344_p2[13 : 1];
        tmp_9_reg_1416 <= tmp_9_fu_350_p2;
        widthloop_reg_1385 <= widthloop_fu_302_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        i_V_reg_1434 <= i_V_fu_387_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) & ~(ap_const_lv1_0 == tmp_4_fu_382_p2))) begin
        icmp_reg_1448 <= icmp_fu_413_p2;
        p_p2_i423_i_1_reg_1497 <= p_p2_i423_i_1_fu_522_p3;
        p_p2_i423_i_2_reg_1512 <= p_p2_i423_i_2_fu_570_p3;
        p_p2_i423_i_reg_1482 <= p_p2_i423_i_fu_474_p3;
        tmp_111_1_reg_1457 <= tmp_111_1_fu_424_p2;
        tmp_111_2_reg_1461 <= tmp_111_2_fu_430_p2;
        tmp_11_reg_1439 <= tmp_11_fu_393_p2;
        tmp_12_reg_1453 <= tmp_12_fu_419_p2;
        tmp_137_1_reg_1492 <= tmp_137_1_fu_503_p2;
        tmp_137_2_reg_1507 <= tmp_137_2_fu_551_p2;
        tmp_13_reg_1465 <= tmp_13_fu_436_p2;
        tmp_16_reg_1477 <= tmp_16_fu_455_p2;
        tmp_22_reg_1472 <= tmp_15_fu_441_p2[ap_const_lv32_C];
        tmp_27_reg_1487 <= p_assign_6_1_fu_489_p2[ap_const_lv32_C];
        tmp_33_reg_1502 <= p_assign_6_2_fu_537_p2[ap_const_lv32_C];
        tmp_47_reg_1517 <= tmp_47_fu_585_p1;
        tmp_49_reg_1522 <= tmp_49_fu_589_p1;
        tmp_53_reg_1527 <= tmp_53_fu_593_p2;
        tmp_55_reg_1532 <= tmp_55_fu_599_p1;
        tmp_56_reg_1537 <= tmp_56_fu_603_p1;
        tmp_58_reg_1542 <= tmp_58_fu_607_p2;
        tmp_59_reg_1547 <= tmp_59_fu_613_p1;
        tmp_60_reg_1552 <= tmp_60_fu_617_p1;
        tmp_61_reg_1557 <= tmp_61_fu_621_p2;
        ult_reg_1443 <= ult_fu_398_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_sig_bdd_227 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_245 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it9))) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i_reg_1658_pp0_it6))) begin
        isneg_reg_1791 <= p_Val2_3_fu_1203_p2[ap_const_lv32_A];
        not_i_i_i_reg_1807 <= not_i_i_i_fu_1236_p2;
        p_Val2_4_reg_1796 <= p_Val2_4_fu_1216_p1;
        tmp_2_i_i_reg_1801 <= tmp_2_i_i_fu_1230_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_sig_bdd_227 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_245 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it9))) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_20_reg_1627_pp0_it2))) begin
        k_buf_0_val_3_addr_reg_1705 <= tmp_29_fu_913_p1;
        k_buf_0_val_4_addr_reg_1711 <= tmp_29_fu_913_p1;
        k_buf_0_val_5_addr_reg_1717 <= tmp_29_fu_913_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~(ap_const_lv1_0 == ap_reg_ppstg_tmp_20_reg_1627_pp0_it3) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4) & ~((ap_sig_bdd_227 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_245 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it9))))) begin
        k_buf_0_val_3_load_reg_1723 <= k_buf_0_val_3_q0;
        k_buf_0_val_4_load_reg_1736 <= k_buf_0_val_4_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_sig_bdd_227 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_245 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it9))) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i_reg_1658_pp0_it7))) begin
        p_Val2_s_reg_1812 <= p_Val2_s_fu_1258_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4)) begin
        rev_reg_1607 <= rev_fu_723_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~(ap_const_lv1_0 == ap_reg_ppstg_tmp_20_reg_1627_pp0_it3) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i_i_reg_1662_pp0_it3) & ~(ap_const_lv1_0 == icmp_reg_1448) & ~(ap_const_lv1_0 == tmp_11_reg_1439) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4) & ~((ap_sig_bdd_227 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_245 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it9))))) begin
        right_border_buf_0_val_0_1_1_fu_162 <= right_border_buf_0_val_0_1_fu_158;
        right_border_buf_0_val_0_1_fu_158 <= col_buf_0_val_0_0_fu_949_p3;
        right_border_buf_0_val_1_1_1_fu_174 <= right_border_buf_0_val_1_1_fu_170;
        right_border_buf_0_val_1_1_fu_170 <= col_buf_0_val_1_0_fu_967_p3;
        right_border_buf_0_val_2_1_1_fu_178 <= col_buf_0_val_2_0_fu_985_p3;
        right_border_buf_0_val_2_1_fu_166 <= right_border_buf_0_val_2_1_1_fu_178;
    end
end

always @ (posedge ap_clk) begin
    if ((~(ap_const_lv1_0 == tmp_13_reg_1465) & (ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4))) begin
        row_assign_9_1_t_reg_1617 <= row_assign_9_1_t_fu_743_p2;
        row_assign_9_2_t_reg_1622 <= row_assign_9_2_t_fu_753_p2;
        row_assign_9_reg_1612 <= row_assign_9_fu_733_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it6) & ~((ap_sig_bdd_227 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_245 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it9))) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_20_reg_1627_pp0_it5))) begin
        src_kernel_win_0_val_0_1_1_fu_138 <= src_kernel_win_0_val_0_1_fu_134;
        src_kernel_win_0_val_0_1_fu_134 <= src_kernel_win_0_val_0_0_reg_1763;
        src_kernel_win_0_val_1_1_1_fu_146 <= src_kernel_win_0_val_1_1_fu_142;
        src_kernel_win_0_val_1_1_fu_142 <= src_kernel_win_0_val_1_0_reg_1769;
        src_kernel_win_0_val_2_1_1_fu_154 <= src_kernel_win_0_val_2_1_fu_150;
        src_kernel_win_0_val_2_1_fu_150 <= src_kernel_win_0_val_2_0_reg_1775;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_sig_bdd_227 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_245 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it9))) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i_reg_1658_pp0_it5))) begin
        tmp25_reg_1781 <= tmp25_fu_1135_p2;
        tmp27_reg_1786 <= tmp27_fu_1141_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~(ap_const_lv1_0 == ap_reg_ppstg_tmp_20_reg_1627_pp0_it3) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i_i_reg_1662_pp0_it3) & (ap_const_lv1_0 == icmp_reg_1448) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4) & ~((ap_sig_bdd_227 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_245 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it9))))) begin
        tmp_71_reg_1757 <= p_src_data_stream_V_dout;
    end
end

always @ (ap_start or ap_sig_cseq_ST_st1_fsm_0 or ap_sig_cseq_ST_st3_fsm_2 or tmp_4_fu_382_p2) begin
    if (((~(ap_const_logic_1 == ap_start) & (ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) & (ap_const_lv1_0 == tmp_4_fu_382_p2)))) begin
        ap_done = ap_const_logic_1;
    end else begin
        ap_done = ap_const_logic_0;
    end
end

always @ (ap_start or ap_sig_cseq_ST_st1_fsm_0) begin
    if ((~(ap_const_logic_1 == ap_start) & (ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0))) begin
        ap_idle = ap_const_logic_1;
    end else begin
        ap_idle = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_st3_fsm_2 or tmp_4_fu_382_p2) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) & (ap_const_lv1_0 == tmp_4_fu_382_p2))) begin
        ap_ready = ap_const_logic_1;
    end else begin
        ap_ready = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_198) begin
    if (ap_sig_bdd_198) begin
        ap_sig_cseq_ST_pp0_stg0_fsm_5 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_pp0_stg0_fsm_5 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_420) begin
    if (ap_sig_bdd_420) begin
        ap_sig_cseq_ST_st16_fsm_6 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st16_fsm_6 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_25) begin
    if (ap_sig_bdd_25) begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_60) begin
    if (ap_sig_bdd_60) begin
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_91) begin
    if (ap_sig_bdd_91) begin
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_154) begin
    if (ap_sig_bdd_154) begin
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_182) begin
    if (ap_sig_bdd_182) begin
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_0;
    end
end

always @ (ap_reg_ppiten_pp0_it3 or ap_sig_bdd_227 or ap_reg_ppiten_pp0_it4 or ap_sig_bdd_245 or ap_reg_ppiten_pp0_it9) begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it3) & ~((ap_sig_bdd_227 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_245 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it9))))) begin
        k_buf_0_val_3_ce0 = ap_const_logic_1;
    end else begin
        k_buf_0_val_3_ce0 = ap_const_logic_0;
    end
end

always @ (tmp_11_reg_1439 or icmp_reg_1448 or tmp_111_2_reg_1461 or ap_reg_ppstg_tmp_20_reg_1627_pp0_it3 or ap_reg_ppstg_or_cond_i_i_reg_1662_pp0_it3 or ap_sig_bdd_227 or ap_reg_ppiten_pp0_it4 or ap_sig_bdd_245 or ap_reg_ppiten_pp0_it9) begin
    if (((~(ap_const_lv1_0 == ap_reg_ppstg_tmp_20_reg_1627_pp0_it3) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i_i_reg_1662_pp0_it3) & ~(ap_const_lv1_0 == icmp_reg_1448) & ~(ap_const_lv1_0 == tmp_11_reg_1439) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4) & ~((ap_sig_bdd_227 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_245 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it9)))) | (~(ap_const_lv1_0 == ap_reg_ppstg_tmp_20_reg_1627_pp0_it3) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i_i_reg_1662_pp0_it3) & (ap_const_lv1_0 == icmp_reg_1448) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4) & ~((ap_sig_bdd_227 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_245 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it9))) & ~(ap_const_lv1_0 == tmp_111_2_reg_1461)))) begin
        k_buf_0_val_3_ce1 = ap_const_logic_1;
    end else begin
        k_buf_0_val_3_ce1 = ap_const_logic_0;
    end
end

always @ (tmp_11_reg_1439 or icmp_reg_1448 or tmp_111_2_reg_1461 or ap_reg_ppstg_tmp_20_reg_1627_pp0_it3 or ap_reg_ppstg_or_cond_i_i_reg_1662_pp0_it3 or ap_sig_bdd_227 or ap_reg_ppiten_pp0_it4 or ap_sig_bdd_245 or ap_reg_ppiten_pp0_it9) begin
    if (((~(ap_const_lv1_0 == ap_reg_ppstg_tmp_20_reg_1627_pp0_it3) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i_i_reg_1662_pp0_it3) & ~(ap_const_lv1_0 == icmp_reg_1448) & ~(ap_const_lv1_0 == tmp_11_reg_1439) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4) & ~((ap_sig_bdd_227 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_245 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it9)))) | (~(ap_const_lv1_0 == ap_reg_ppstg_tmp_20_reg_1627_pp0_it3) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i_i_reg_1662_pp0_it3) & (ap_const_lv1_0 == icmp_reg_1448) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4) & ~((ap_sig_bdd_227 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_245 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it9))) & ~(ap_const_lv1_0 == tmp_111_2_reg_1461)))) begin
        k_buf_0_val_3_we1 = ap_const_logic_1;
    end else begin
        k_buf_0_val_3_we1 = ap_const_logic_0;
    end
end

always @ (ap_reg_ppiten_pp0_it3 or ap_sig_bdd_227 or ap_reg_ppiten_pp0_it4 or ap_sig_bdd_245 or ap_reg_ppiten_pp0_it9) begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it3) & ~((ap_sig_bdd_227 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_245 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it9))))) begin
        k_buf_0_val_4_ce0 = ap_const_logic_1;
    end else begin
        k_buf_0_val_4_ce0 = ap_const_logic_0;
    end
end

always @ (tmp_11_reg_1439 or icmp_reg_1448 or tmp_111_1_reg_1457 or ap_sig_bdd_227 or ap_reg_ppiten_pp0_it4 or ap_reg_ppiten_pp0_it5 or ap_sig_bdd_245 or ap_reg_ppiten_pp0_it9 or ap_reg_ppstg_or_cond_i_i_reg_1662_pp0_it4) begin
    if ((((ap_const_lv1_0 == icmp_reg_1448) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5) & ~((ap_sig_bdd_227 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_245 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it9))) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i_i_reg_1662_pp0_it4) & ~(ap_const_lv1_0 == tmp_111_1_reg_1457)) | (~(ap_const_lv1_0 == icmp_reg_1448) & ~(ap_const_lv1_0 == tmp_11_reg_1439) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5) & ~((ap_sig_bdd_227 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_245 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it9))) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i_i_reg_1662_pp0_it4)))) begin
        k_buf_0_val_4_ce1 = ap_const_logic_1;
    end else begin
        k_buf_0_val_4_ce1 = ap_const_logic_0;
    end
end

always @ (k_buf_0_val_3_load_reg_1723 or tmp_71_reg_1757 or ap_sig_bdd_1131 or ap_sig_bdd_1133 or ap_sig_bdd_1130) begin
    if (ap_sig_bdd_1130) begin
        if (ap_sig_bdd_1133) begin
            k_buf_0_val_4_d1 = k_buf_0_val_3_load_reg_1723;
        end else if (ap_sig_bdd_1131) begin
            k_buf_0_val_4_d1 = tmp_71_reg_1757;
        end else begin
            k_buf_0_val_4_d1 = 'bx;
        end
    end else begin
        k_buf_0_val_4_d1 = 'bx;
    end
end

always @ (tmp_11_reg_1439 or icmp_reg_1448 or tmp_111_1_reg_1457 or ap_sig_bdd_227 or ap_reg_ppiten_pp0_it4 or ap_reg_ppiten_pp0_it5 or ap_sig_bdd_245 or ap_reg_ppiten_pp0_it9 or ap_reg_ppstg_or_cond_i_i_reg_1662_pp0_it4) begin
    if ((((ap_const_lv1_0 == icmp_reg_1448) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5) & ~((ap_sig_bdd_227 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_245 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it9))) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i_i_reg_1662_pp0_it4) & ~(ap_const_lv1_0 == tmp_111_1_reg_1457)) | (~(ap_const_lv1_0 == icmp_reg_1448) & ~(ap_const_lv1_0 == tmp_11_reg_1439) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5) & ~((ap_sig_bdd_227 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_245 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it9))) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i_i_reg_1662_pp0_it4)))) begin
        k_buf_0_val_4_we1 = ap_const_logic_1;
    end else begin
        k_buf_0_val_4_we1 = ap_const_logic_0;
    end
end

always @ (ap_reg_ppiten_pp0_it3 or ap_sig_bdd_227 or ap_reg_ppiten_pp0_it4 or ap_sig_bdd_245 or ap_reg_ppiten_pp0_it9) begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it3) & ~((ap_sig_bdd_227 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_245 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it9))))) begin
        k_buf_0_val_5_ce0 = ap_const_logic_1;
    end else begin
        k_buf_0_val_5_ce0 = ap_const_logic_0;
    end
end

always @ (tmp_11_reg_1439 or icmp_reg_1448 or tmp_12_reg_1453 or ap_sig_bdd_227 or ap_reg_ppiten_pp0_it4 or ap_reg_ppiten_pp0_it5 or ap_sig_bdd_245 or ap_reg_ppiten_pp0_it9 or ap_reg_ppstg_or_cond_i_i_reg_1662_pp0_it4) begin
    if (((~(ap_const_lv1_0 == icmp_reg_1448) & ~(ap_const_lv1_0 == tmp_11_reg_1439) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5) & ~((ap_sig_bdd_227 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_245 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it9))) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i_i_reg_1662_pp0_it4)) | ((ap_const_lv1_0 == icmp_reg_1448) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5) & ~((ap_sig_bdd_227 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_245 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it9))) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i_i_reg_1662_pp0_it4) & ~(ap_const_lv1_0 == tmp_12_reg_1453)))) begin
        k_buf_0_val_5_ce1 = ap_const_logic_1;
    end else begin
        k_buf_0_val_5_ce1 = ap_const_logic_0;
    end
end

always @ (k_buf_0_val_4_load_reg_1736 or tmp_71_reg_1757 or ap_sig_bdd_1133 or ap_sig_bdd_1130 or ap_sig_bdd_1136) begin
    if (ap_sig_bdd_1130) begin
        if (ap_sig_bdd_1133) begin
            k_buf_0_val_5_d1 = k_buf_0_val_4_load_reg_1736;
        end else if (ap_sig_bdd_1136) begin
            k_buf_0_val_5_d1 = tmp_71_reg_1757;
        end else begin
            k_buf_0_val_5_d1 = 'bx;
        end
    end else begin
        k_buf_0_val_5_d1 = 'bx;
    end
end

always @ (tmp_11_reg_1439 or icmp_reg_1448 or tmp_12_reg_1453 or ap_sig_bdd_227 or ap_reg_ppiten_pp0_it4 or ap_reg_ppiten_pp0_it5 or ap_sig_bdd_245 or ap_reg_ppiten_pp0_it9 or ap_reg_ppstg_or_cond_i_i_reg_1662_pp0_it4) begin
    if (((~(ap_const_lv1_0 == icmp_reg_1448) & ~(ap_const_lv1_0 == tmp_11_reg_1439) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5) & ~((ap_sig_bdd_227 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_245 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it9))) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i_i_reg_1662_pp0_it4)) | ((ap_const_lv1_0 == icmp_reg_1448) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it5) & ~((ap_sig_bdd_227 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_245 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it9))) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i_i_reg_1662_pp0_it4) & ~(ap_const_lv1_0 == tmp_12_reg_1453)))) begin
        k_buf_0_val_5_we1 = ap_const_logic_1;
    end else begin
        k_buf_0_val_5_we1 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_227 or ap_reg_ppiten_pp0_it4 or ap_reg_ppstg_or_cond_i_reg_1658_pp0_it8 or ap_sig_bdd_245 or ap_reg_ppiten_pp0_it9) begin
    if ((~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i_reg_1658_pp0_it8) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it9) & ~((ap_sig_bdd_227 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_245 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it9))))) begin
        p_dst_data_stream_V_write = ap_const_logic_1;
    end else begin
        p_dst_data_stream_V_write = ap_const_logic_0;
    end
end

always @ (tmp_11_reg_1439 or icmp_reg_1448 or ap_reg_ppstg_tmp_20_reg_1627_pp0_it3 or ap_reg_ppstg_or_cond_i_i_reg_1662_pp0_it3 or ap_sig_bdd_227 or ap_reg_ppiten_pp0_it4 or ap_sig_bdd_245 or ap_reg_ppiten_pp0_it9) begin
    if (((~(ap_const_lv1_0 == ap_reg_ppstg_tmp_20_reg_1627_pp0_it3) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i_i_reg_1662_pp0_it3) & (ap_const_lv1_0 == icmp_reg_1448) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4) & ~((ap_sig_bdd_227 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_245 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it9)))) | (~(ap_const_lv1_0 == ap_reg_ppstg_tmp_20_reg_1627_pp0_it3) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i_i_reg_1662_pp0_it3) & ~(ap_const_lv1_0 == icmp_reg_1448) & ~(ap_const_lv1_0 == tmp_11_reg_1439) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4) & ~((ap_sig_bdd_227 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_245 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it9)))))) begin
        p_src_data_stream_V_read = ap_const_logic_1;
    end else begin
        p_src_data_stream_V_read = ap_const_logic_0;
    end
end
always @ (ap_start or ap_CS_fsm or tmp_6_phi_fu_254_p4 or tmp_4_fu_382_p2 or ap_reg_ppiten_pp0_it3 or ap_sig_bdd_227 or ap_reg_ppiten_pp0_it4 or ap_reg_ppiten_pp0_it5 or ap_reg_ppiten_pp0_it8 or ap_sig_bdd_245 or ap_reg_ppiten_pp0_it9) begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : 
        begin
            if (~(ap_start == ap_const_logic_0)) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end
        end
        ap_ST_st2_fsm_1 : 
        begin
            if ((tmp_6_phi_fu_254_p4 == ap_const_lv1_0)) begin
                ap_NS_fsm = ap_ST_st3_fsm_2;
            end else begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end
        end
        ap_ST_st3_fsm_2 : 
        begin
            if ((ap_const_lv1_0 == tmp_4_fu_382_p2)) begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end else begin
                ap_NS_fsm = ap_ST_st4_fsm_3;
            end
        end
        ap_ST_st4_fsm_3 : 
        begin
            ap_NS_fsm = ap_ST_st5_fsm_4;
        end
        ap_ST_st5_fsm_4 : 
        begin
            ap_NS_fsm = ap_ST_pp0_stg0_fsm_5;
        end
        ap_ST_pp0_stg0_fsm_5 : 
        begin
            if ((~((ap_const_logic_1 == ap_reg_ppiten_pp0_it9) & ~((ap_sig_bdd_227 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_245 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it9))) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it8)) & ~((ap_const_logic_1 == ap_reg_ppiten_pp0_it4) & ~((ap_sig_bdd_227 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_245 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it9))) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it3) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it5)))) begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_5;
            end else if ((((ap_const_logic_1 == ap_reg_ppiten_pp0_it9) & ~((ap_sig_bdd_227 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_245 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it9))) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it8)) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it4) & ~((ap_sig_bdd_227 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it4)) | (ap_sig_bdd_245 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it9))) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it3) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it5)))) begin
                ap_NS_fsm = ap_ST_st16_fsm_6;
            end else begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_5;
            end
        end
        ap_ST_st16_fsm_6 : 
        begin
            ap_NS_fsm = ap_ST_st3_fsm_2;
        end
        default : 
        begin
            ap_NS_fsm = 'bx;
        end
    endcase
end


assign ImagLoc_x_cast_mux_cast_fu_857_p1 = ImagLoc_x_cast_mux_fu_850_p3;

assign ImagLoc_x_cast_mux_fu_850_p3 = ((or_cond_i_i_fu_841_p2[0:0] === 1'b1) ? ImagLoc_x_reg_1636 : ap_const_lv13_0);

assign ImagLoc_x_fu_789_p2 = ($signed(ap_const_lv13_1FFF) + $signed(tmp_19_cast_fu_758_p1));

assign OP1_V_0_cast_fu_1079_p1 = src_kernel_win_0_val_2_1_1_fu_154;

assign OP1_V_2_cast_fu_1118_p1 = src_kernel_win_0_val_0_1_1_fu_138;


always @ (ap_reg_ppiten_pp0_it5 or ap_reg_ppstg_or_cond_i_i_reg_1662_pp0_it4) begin
    ap_sig_bdd_1130 = ((ap_const_logic_1 == ap_reg_ppiten_pp0_it5) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i_i_reg_1662_pp0_it4));
end


always @ (icmp_reg_1448 or tmp_111_1_reg_1457) begin
    ap_sig_bdd_1131 = ((ap_const_lv1_0 == icmp_reg_1448) & ~(ap_const_lv1_0 == tmp_111_1_reg_1457));
end


always @ (tmp_11_reg_1439 or icmp_reg_1448) begin
    ap_sig_bdd_1133 = (~(ap_const_lv1_0 == icmp_reg_1448) & ~(ap_const_lv1_0 == tmp_11_reg_1439));
end


always @ (icmp_reg_1448 or tmp_12_reg_1453) begin
    ap_sig_bdd_1136 = ((ap_const_lv1_0 == icmp_reg_1448) & ~(ap_const_lv1_0 == tmp_12_reg_1453));
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_154 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_3]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_182 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_4]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_198 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_5]);
end


always @ (p_src_data_stream_V_empty_n or tmp_11_reg_1439 or icmp_reg_1448 or ap_reg_ppstg_tmp_20_reg_1627_pp0_it3 or ap_reg_ppstg_or_cond_i_i_reg_1662_pp0_it3) begin
    ap_sig_bdd_227 = (((p_src_data_stream_V_empty_n == ap_const_logic_0) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_20_reg_1627_pp0_it3) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i_i_reg_1662_pp0_it3) & (ap_const_lv1_0 == icmp_reg_1448)) | ((p_src_data_stream_V_empty_n == ap_const_logic_0) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_20_reg_1627_pp0_it3) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i_i_reg_1662_pp0_it3) & ~(ap_const_lv1_0 == icmp_reg_1448) & ~(ap_const_lv1_0 == tmp_11_reg_1439)));
end


always @ (p_dst_data_stream_V_full_n or ap_reg_ppstg_or_cond_i_reg_1658_pp0_it8) begin
    ap_sig_bdd_245 = ((p_dst_data_stream_V_full_n == ap_const_logic_0) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond_i_reg_1658_pp0_it8));
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_25 = (ap_CS_fsm[ap_const_lv32_0] == ap_const_lv1_1);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_420 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_6]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_60 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_1]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_91 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_2]);
end

assign brmerge1_fu_669_p2 = (or_cond_i422_i_fu_632_p2 | tmp_1_reg_1402);

assign brmerge2_fu_687_p2 = (or_cond_i422_i_1_fu_646_p2 | tmp_1_reg_1402);

assign brmerge3_fu_705_p2 = (or_cond_i422_i_2_fu_660_p2 | tmp_1_reg_1402);

assign brmerge9_fu_845_p2 = (or_cond_i_i_fu_841_p2 | tmp_9_reg_1416);

assign brmerge_fu_887_p2 = (rev_reg_1607 | tmp_25_reg_1646);

assign col_assign_2_t_fu_905_p2 = (tmp_3_reg_1426 - tmp_65_fu_901_p1);

assign col_assign_cast_fu_910_p1 = $signed(x_reg_1693);

assign col_buf_0_val_0_0_fu_949_p3 = ((ap_reg_ppstg_brmerge_reg_1686_pp0_it3[0:0] === 1'b1) ? k_buf_0_val_3_q0 : tmp_34_fu_938_p5);

assign col_buf_0_val_1_0_fu_967_p3 = ((ap_reg_ppstg_brmerge_reg_1686_pp0_it3[0:0] === 1'b1) ? k_buf_0_val_4_q0 : tmp_35_fu_956_p5);

assign col_buf_0_val_2_0_fu_985_p3 = ((ap_reg_ppstg_brmerge_reg_1686_pp0_it3[0:0] === 1'b1) ? k_buf_0_val_5_q0 : tmp_36_fu_974_p5);

assign cols_cast_fu_287_p1 = p_src_cols_V_read;

assign heightloop_fu_297_p2 = (ap_const_lv13_2 + rows_cast_reg_1283);

assign i_V_fu_387_p2 = (p_014_0_i_reg_261 + ap_const_lv12_1);

assign icmp1_fu_783_p2 = (tmp_62_fu_773_p4 != ap_const_lv11_0? 1'b1: 1'b0);

assign icmp_fu_413_p2 = (tmp_18_fu_403_p4 != ap_const_lv11_0? 1'b1: 1'b0);

assign isneg_fu_1208_p3 = p_Val2_3_fu_1203_p2[ap_const_lv32_A];

assign j_V_fu_767_p2 = (p_027_0_i_reg_272 + ap_const_lv12_1);

assign k_buf_0_val_3_address0 = tmp_29_fu_913_p1;

assign k_buf_0_val_3_address1 = k_buf_0_val_3_addr_reg_1705;

assign k_buf_0_val_3_d1 = p_src_data_stream_V_dout;

assign k_buf_0_val_4_address0 = tmp_29_fu_913_p1;

assign k_buf_0_val_4_address1 = ap_reg_ppstg_k_buf_0_val_4_addr_reg_1711_pp0_it4;

assign k_buf_0_val_5_address0 = tmp_29_fu_913_p1;

assign k_buf_0_val_5_address1 = ap_reg_ppstg_k_buf_0_val_5_addr_reg_1717_pp0_it4;

assign not_i_i_i_fu_1236_p2 = (tmp_52_fu_1220_p4 != ap_const_lv3_0? 1'b1: 1'b0);

assign not_tmp_s_fu_319_p2 = (p_src_rows_V_read != ap_const_lv12_1? 1'b1: 1'b0);

assign or_cond_i422_i_1_fu_646_p2 = (tmp_137_1_reg_1492 & rev2_fu_641_p2);

assign or_cond_i422_i_2_fu_660_p2 = (tmp_137_2_reg_1507 & rev3_fu_655_p2);

assign or_cond_i422_i_fu_632_p2 = (tmp_16_reg_1477 & rev1_fu_627_p2);

assign or_cond_i_fu_836_p2 = (icmp_reg_1448 & icmp1_fu_783_p2);

assign or_cond_i_i_fu_841_p2 = (tmp_25_reg_1646 & rev4_reg_1641);

assign overflow_fu_1242_p2 = (not_i_i_i_reg_1807 & tmp_2_i_i_reg_1801);

assign p_Val2_1_2_fu_1183_p3 = {{ap_reg_ppstg_src_kernel_win_0_val_1_0_reg_1769_pp0_it6}, {ap_const_lv1_0}};

assign p_Val2_1_fu_1108_p2 = (ap_const_lv10_0 - p_shl_cast_fu_1104_p1);

assign p_Val2_2_fu_1122_p2 = (ap_const_lv9_0 - OP1_V_2_cast_fu_1118_p1);

assign p_Val2_3_fu_1203_p2 = (tmp25_reg_1781 + tmp26_fu_1197_p2);

assign p_Val2_4_fu_1216_p1 = p_Val2_3_fu_1203_p2[7:0];

assign p_Val2_5_0_2_cast_cast_fu_1092_p1 = $signed(p_Val2_5_0_2_fu_1086_p2);

assign p_Val2_5_0_2_fu_1086_p2 = (tmp_155_0_2_cast_fu_1083_p1 - OP1_V_0_cast_fu_1079_p1);

assign p_Val2_s_fu_1258_p3 = ((tmp_i_i_fu_1253_p2[0:0] === 1'b1) ? p_mux_i_i_cast_fu_1246_p3 : p_Val2_4_reg_1796);

assign p_anchor_2_1_cast_fu_324_p1 = not_tmp_s_fu_319_p2;

assign p_assign_1_fu_822_p2 = (ap_const_lv13_1 - tmp_19_cast_fu_758_p1);

assign p_assign_2_fu_868_p2 = ($signed(tmp_2_reg_1421) - $signed(p_p2_i_i_cast_fu_861_p1));

assign p_assign_6_1_fu_489_p2 = ($signed(ap_const_lv13_1FFE) + $signed(tmp_15_cast_fu_378_p1));

assign p_assign_6_2_fu_537_p2 = ($signed(ap_const_lv13_1FFD) + $signed(tmp_15_cast_fu_378_p1));

assign p_assign_7_1_fu_516_p2 = (ap_const_lv13_2 - tmp_15_cast_fu_378_p1);

assign p_assign_7_2_fu_564_p2 = (ap_const_lv13_3 - tmp_15_cast_fu_378_p1);

assign p_assign_7_fu_468_p2 = (ap_const_lv13_1 - tmp_15_cast_fu_378_p1);

assign p_dst_data_stream_V_din = p_Val2_s_reg_1812;

assign p_mux_i_i_cast_fu_1246_p3 = ((tmp_2_i_i_reg_1801[0:0] === 1'b1) ? ap_const_lv8_FF : ap_const_lv8_0);

assign p_neg391_i_cast_fu_310_p2 = ($signed(ap_const_lv2_3) + $signed(tmp_fu_307_p1));

assign p_p2_i423_i_1_fu_522_p3 = ((tmp_30_fu_508_p3[0:0] === 1'b1) ? p_assign_7_1_fu_516_p2 : p_assign_6_1_fu_489_p2);

assign p_p2_i423_i_2_fu_570_p3 = ((tmp_38_fu_556_p3[0:0] === 1'b1) ? p_assign_7_2_fu_564_p2 : p_assign_6_2_fu_537_p2);

assign p_p2_i423_i_fu_474_p3 = ((tmp_23_fu_460_p3[0:0] === 1'b1) ? p_assign_7_fu_468_p2 : tmp_15_fu_441_p2);

assign p_p2_i_i_cast_fu_861_p1 = $signed(p_p2_i_i_reg_1652);

assign p_p2_i_i_fu_828_p3 = ((tmp_64_fu_814_p3[0:0] === 1'b1) ? p_assign_1_fu_822_p2 : ImagLoc_x_fu_789_p2);

assign p_shl_cast_fu_1104_p1 = p_shl_fu_1096_p3;

assign p_shl_fu_1096_p3 = {{src_kernel_win_0_val_1_1_1_fu_146}, {ap_const_lv1_0}};

assign rev1_fu_627_p2 = (tmp_22_reg_1472 ^ ap_const_lv1_1);

assign rev2_fu_641_p2 = (tmp_27_reg_1487 ^ ap_const_lv1_1);

assign rev3_fu_655_p2 = (tmp_33_reg_1502 ^ ap_const_lv1_1);

assign rev4_fu_803_p2 = (tmp_63_fu_795_p3 ^ ap_const_lv1_1);

assign rev_fu_723_p2 = (ult_reg_1443 ^ ap_const_lv1_1);

assign row_assign_9_1_t_fu_743_p2 = (p_neg391_i_cast_reg_1390 - tmp_45_fu_738_p3);

assign row_assign_9_2_t_fu_753_p2 = (p_neg391_i_cast_reg_1390 - tmp_50_fu_748_p3);

assign row_assign_9_fu_733_p2 = (p_neg391_i_cast_reg_1390 - tmp_40_fu_728_p3);

assign rows_cast_fu_283_p1 = p_src_rows_V_read;

assign sel_tmp7_fu_881_p2 = (brmerge9_fu_845_p2 ^ ap_const_lv1_1);

assign sel_tmp8_fu_891_p2 = (tmp_28_reg_1671 & sel_tmp7_reg_1681);

assign sel_tmp_fu_873_p3 = ((brmerge9_fu_845_p2[0:0] === 1'b1) ? ImagLoc_x_cast_mux_cast_fu_857_p1 : p_assign_2_fu_868_p2);

assign src_kernel_win_0_val_0_0_fu_1036_p3 = ((tmp_13_reg_1465[0:0] === 1'b1) ? tmp_41_fu_1028_p5 : col_buf_0_val_0_0_reg_1728);

assign src_kernel_win_0_val_1_0_fu_1050_p3 = ((tmp_13_reg_1465[0:0] === 1'b1) ? tmp_46_fu_1042_p5 : col_buf_0_val_1_0_reg_1741);

assign src_kernel_win_0_val_2_0_fu_1064_p3 = ((tmp_13_reg_1465[0:0] === 1'b1) ? tmp_51_fu_1056_p5 : col_buf_0_val_2_0_reg_1749);

assign tmp25_fu_1135_p2 = ($signed(tmp_155_2_cast_fu_1128_p1) + $signed(tmp_155_1_cast_fu_1114_p1));

assign tmp26_fu_1197_p2 = ($signed(tmp_155_1_cast_38_fu_1190_p1) + $signed(tmp27_cast_fu_1194_p1));

assign tmp27_cast_fu_1194_p1 = $signed(tmp27_reg_1786);

assign tmp27_fu_1141_p2 = ($signed(tmp_155_2_2_cast_cast_fu_1132_p1) + $signed(p_Val2_5_0_2_cast_cast_fu_1092_p1));

assign tmp_111_1_fu_424_p2 = (p_014_0_i_reg_261 == ap_const_lv12_0? 1'b1: 1'b0);

assign tmp_111_2_fu_430_p2 = (p_014_0_i_reg_261 == ap_const_lv12_1? 1'b1: 1'b0);

assign tmp_11_fu_393_p2 = (p_014_0_i_reg_261 < p_src_rows_V_read? 1'b1: 1'b0);

assign tmp_12_fu_419_p2 = (p_anchor_2_1_cast_reg_1397 == tmp_15_cast_fu_378_p1? 1'b1: 1'b0);

assign tmp_137_1_fu_503_p2 = ($signed(p_assign_6_1_fu_489_p2) < $signed(rows_cast_reg_1283)? 1'b1: 1'b0);

assign tmp_137_2_fu_551_p2 = ($signed(p_assign_6_2_fu_537_p2) < $signed(rows_cast_reg_1283)? 1'b1: 1'b0);

assign tmp_13_fu_436_p2 = (p_014_0_i_reg_261 > p_src_rows_V_read? 1'b1: 1'b0);

assign tmp_147_1_fu_651_p2 = ($signed(p_p2_i423_i_1_reg_1497) < $signed(rows_cast_reg_1283)? 1'b1: 1'b0);

assign tmp_147_2_fu_665_p2 = ($signed(p_p2_i423_i_2_reg_1512) < $signed(rows_cast_reg_1283)? 1'b1: 1'b0);

assign tmp_149_cast_fu_340_p1 = tmp_5_fu_333_p3;

assign tmp_14_fu_316_p1 = p_src_cols_V_read[1:0];

assign tmp_155_0_2_cast_fu_1083_p1 = src_kernel_win_0_val_2_0_reg_1775;

assign tmp_155_1_cast_38_fu_1190_p1 = p_Val2_1_2_fu_1183_p3;

assign tmp_155_1_cast_fu_1114_p1 = $signed(p_Val2_1_fu_1108_p2);

assign tmp_155_2_2_cast_cast_fu_1132_p1 = src_kernel_win_0_val_0_0_reg_1763;

assign tmp_155_2_cast_fu_1128_p1 = $signed(p_Val2_2_fu_1122_p2);

assign tmp_15_cast_fu_378_p1 = p_014_0_i_reg_261;

assign tmp_15_fu_441_p2 = ($signed(ap_const_lv13_1FFF) + $signed(tmp_15_cast_fu_378_p1));

assign tmp_16_fu_455_p2 = ($signed(tmp_15_fu_441_p2) < $signed(rows_cast_reg_1283)? 1'b1: 1'b0);

assign tmp_17_fu_637_p2 = ($signed(p_p2_i423_i_reg_1482) < $signed(rows_cast_reg_1283)? 1'b1: 1'b0);

assign tmp_18_fu_403_p4 = {{p_014_0_i_reg_261[ap_const_lv32_B : ap_const_lv32_1]}};

assign tmp_19_cast_fu_758_p1 = p_027_0_i_reg_272;

assign tmp_19_fu_674_p3 = ((or_cond_i422_i_fu_632_p2[0:0] === 1'b1) ? tmp_47_reg_1517 : ap_const_lv2_0);

assign tmp_1_fu_328_p2 = (p_src_rows_V_read == ap_const_lv12_1? 1'b1: 1'b0);

assign tmp_20_fu_762_p2 = (tmp_19_cast_fu_758_p1 < widthloop_reg_1385? 1'b1: 1'b0);

assign tmp_23_fu_460_p3 = tmp_15_fu_441_p2[ap_const_lv32_C];

assign tmp_24_fu_482_p1 = tmp_8_reg_1409[1:0];

assign tmp_25_fu_809_p2 = ($signed(ImagLoc_x_fu_789_p2) < $signed(cols_cast_reg_1294)? 1'b1: 1'b0);

assign tmp_26_fu_485_p1 = p_p2_i423_i_fu_474_p3[1:0];

assign tmp_28_fu_864_p2 = ($signed(p_p2_i_i_reg_1652) < $signed(cols_cast_reg_1294)? 1'b1: 1'b0);

assign tmp_29_cast_fu_362_p1 = tmp_s_fu_355_p3;

assign tmp_29_fu_913_p1 = $unsigned(col_assign_cast_fu_910_p1);

assign tmp_2_fu_366_p2 = ($signed(ap_const_lv14_3FFE) + $signed(tmp_29_cast_fu_362_p1));

assign tmp_2_i_i_fu_1230_p2 = (isneg_fu_1208_p3 ^ ap_const_lv1_1);

assign tmp_30_fu_508_p3 = p_assign_6_1_fu_489_p2[ap_const_lv32_C];

assign tmp_31_fu_530_p1 = tmp_8_reg_1409[1:0];

assign tmp_32_fu_533_p1 = p_p2_i423_i_1_fu_522_p3[1:0];

assign tmp_37_fu_681_p3 = ((tmp_17_fu_637_p2[0:0] === 1'b1) ? tmp_49_reg_1522 : tmp_53_reg_1527);

assign tmp_38_fu_556_p3 = p_assign_6_2_fu_537_p2[ap_const_lv32_C];

assign tmp_39_fu_578_p1 = tmp_8_reg_1409[1:0];

assign tmp_3_fu_372_p2 = ($signed(ap_const_lv2_3) + $signed(tmp_14_fu_316_p1));

assign tmp_40_fu_728_p3 = ((brmerge1_reg_1562[0:0] === 1'b1) ? tmp_19_reg_1567 : tmp_37_reg_1572);

assign tmp_42_fu_581_p1 = p_p2_i423_i_2_fu_570_p3[1:0];

assign tmp_43_fu_692_p3 = ((or_cond_i422_i_1_fu_646_p2[0:0] === 1'b1) ? tmp_55_reg_1532 : ap_const_lv2_0);

assign tmp_44_fu_699_p3 = ((tmp_147_1_fu_651_p2[0:0] === 1'b1) ? tmp_56_reg_1537 : tmp_58_reg_1542);

assign tmp_45_fu_738_p3 = ((brmerge2_reg_1577[0:0] === 1'b1) ? tmp_43_reg_1582 : tmp_44_reg_1587);

assign tmp_47_fu_585_p1 = tmp_15_fu_441_p2[1:0];

assign tmp_48_fu_710_p3 = ((or_cond_i422_i_2_fu_660_p2[0:0] === 1'b1) ? tmp_59_reg_1547 : ap_const_lv2_0);

assign tmp_49_fu_589_p1 = p_p2_i423_i_fu_474_p3[1:0];

assign tmp_4_fu_382_p2 = (tmp_15_cast_fu_378_p1 < heightloop_reg_1380? 1'b1: 1'b0);

assign tmp_50_fu_748_p3 = ((brmerge3_reg_1592[0:0] === 1'b1) ? tmp_48_reg_1597 : tmp_54_reg_1602);

assign tmp_52_fu_1220_p4 = {{p_Val2_3_fu_1203_p2[ap_const_lv32_A : ap_const_lv32_8]}};

assign tmp_53_fu_593_p2 = (tmp_24_fu_482_p1 - tmp_26_fu_485_p1);

assign tmp_54_fu_717_p3 = ((tmp_147_2_fu_665_p2[0:0] === 1'b1) ? tmp_60_reg_1552 : tmp_61_reg_1557);

assign tmp_55_fu_599_p1 = p_assign_6_1_fu_489_p2[1:0];

assign tmp_56_fu_603_p1 = p_p2_i423_i_1_fu_522_p3[1:0];

assign tmp_58_fu_607_p2 = (tmp_31_fu_530_p1 - tmp_32_fu_533_p1);

assign tmp_59_fu_613_p1 = p_assign_6_2_fu_537_p2[1:0];

assign tmp_5_fu_333_p3 = {{p_src_rows_V_read}, {ap_const_lv1_0}};

assign tmp_60_fu_617_p1 = p_p2_i423_i_2_fu_570_p3[1:0];

assign tmp_61_fu_621_p2 = (tmp_39_fu_578_p1 - tmp_42_fu_581_p1);

assign tmp_62_fu_773_p4 = {{p_027_0_i_reg_272[ap_const_lv32_B : ap_const_lv32_1]}};

assign tmp_63_fu_795_p3 = ImagLoc_x_fu_789_p2[ap_const_lv32_C];

assign tmp_64_fu_814_p3 = ImagLoc_x_fu_789_p2[ap_const_lv32_C];

assign tmp_65_fu_901_p1 = x_fu_895_p3[1:0];

assign tmp_6_phi_fu_254_p4 = tmp_6_reg_250;

assign tmp_7_fu_291_p2 = (tmp_6_reg_250 ^ ap_const_lv1_1);

assign tmp_8_fu_344_p2 = (ap_const_lv14_2 + tmp_149_cast_fu_340_p1);

assign tmp_9_fu_350_p2 = (p_src_cols_V_read == ap_const_lv12_1? 1'b1: 1'b0);

assign tmp_fu_307_p1 = p_src_rows_V_read[1:0];

assign tmp_i_i_fu_1253_p2 = (isneg_reg_1791 | overflow_fu_1242_p2);

assign tmp_s_fu_355_p3 = {{p_src_cols_V_read}, {ap_const_lv1_0}};

assign ult_fu_398_p2 = (p_014_0_i_reg_261 < p_src_rows_V_read? 1'b1: 1'b0);

assign widthloop_fu_302_p2 = (ap_const_lv13_2 + cols_cast_reg_1294);

assign x_fu_895_p3 = ((sel_tmp8_fu_891_p2[0:0] === 1'b1) ? p_p2_i_i_cast_reg_1666 : sel_tmp_reg_1676);
always @ (posedge ap_clk) begin
    rows_cast_reg_1283[12] <= 1'b0;
    cols_cast_reg_1294[12] <= 1'b0;
    p_anchor_2_1_cast_reg_1397[12:1] <= 12'b000000000000;
    tmp_8_reg_1409[0] <= 1'b0;
    tmp_2_reg_1421[0] <= 1'b0;
end



endmodule //newsob_Filter2D

