// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xnewsob.h"

extern XNewsob_Config XNewsob_ConfigTable[];

XNewsob_Config *XNewsob_LookupConfig(u16 DeviceId) {
	XNewsob_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XNEWSOB_NUM_INSTANCES; Index++) {
		if (XNewsob_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XNewsob_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XNewsob_Initialize(XNewsob *InstancePtr, u16 DeviceId) {
	XNewsob_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XNewsob_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XNewsob_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

